# Generated by Django 4.1.7 on 2023-04-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
