# Generated by Django 4.1.7 on 2023-04-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0003_rename_update_at_user_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
