# Generated by Django 4.1.7 on 2023-04-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0005_rename_update_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
