# Generated by Django 4.2 on 2023-04-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0008_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
