# Generated by Django 4.2 on 2023-05-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='product_id',
            field=models.CharField(default='0', max_length=160),
        ),
    ]
