# Generated by Django 4.1.7 on 2023-03-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sliders'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='image',
            field=models.ImageField(default='', upload_to='products/images'),
        ),
    ]
