# Generated by Django 4.1.7 on 2023-03-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sliders_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.IntegerField(default=0)),
            ],
        ),
    ]
