# Generated by Django 4.2 on 2023-05-10 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_popularproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsimage',
            name='popularproduct',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.popularproduct'),
        ),
    ]
