# Generated by Django 4.2 on 2023-05-10 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productsimage_popularproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsimage',
            name='popularproduct',
        ),
        migrations.CreateModel(
            name='PopularProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images')),
                ('popularproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.popularproduct')),
            ],
        ),
    ]
